version: '3.7'
services:
  db_media:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_media'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3309
    ports:
      - '3309:3309'
    expose:
      - '3309'
    volumes:
      - my-db_media:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  web:
    build: .
    environment:
      DB_URI: "mysql+pymysql://user:password@db_media:3309/db_media"
      POSTER_URL: "http://http://serviceweb_netflix_poster-web-1:8091"
      COMPTE_URL: "http://serviceweb_netflix_compte-web-1:8090"
    ports :
      - 8092:8092
    networks:
      - mynetwork
    depends_on:
      db_media:
        condition: service_healthy
volumes:
  my-db_media:
networks:
  mynetwork:
    name: "mynetwork"